name: Teleport2Lobby
main: com.yellowfortyfour.bungee.teleport2lobby.Teleport2LobbyPlugin
version: 0.1.0-SNAPSHOT
author: Fredrik Andersson (ProtonCavor)

commands:
   lobby:
      description: Sends player to lobby server
      usage: /<command>
