name: Teleport2Lobby
main: com.yellowfortyfour.bungee.teleport2lobby.Teleport2LobbyPlugin
version: 0.1.1
author: Fredrik Andersson (ProtonCavor)

commands:
  lobby:
    aliases: hub
    description: Sends player to the lobby server
    usage: /<command>
